package ufrn.kael.distributedPaxos.stateful;

import ufrn.kael.distributedPaxos.common.message.ApplicationCommand;
import ufrn.kael.distributedPaxos.common.message.ApplicationResponse;
import ufrn.kael.distributedPaxos.common.message.Heartbeat;
import ufrn.kael.distributedPaxos.common.message.Message;
import ufrn.kael.distributedPaxos.common.message.PaxosCommand;
import ufrn.kael.distributedPaxos.common.message.Transaction;
import ufrn.kael.distributedPaxos.common.transport.MessageReceiver;
import ufrn.kael.distributedPaxos.common.transport.NetworkRouter;
import ufrn.kael.distributedPaxos.common.transport.Protocol;
import ufrn.kael.distributedPaxos.common.Node;
import ufrn.kael.distributedPaxos.paxos.PaxosEngine;
import ufrn.kael.distributedPaxos.stateful.state.InMemoryDatabase;
import ufrn.kael.distributedPaxos.stateful.state.DatabaseStateMachine;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class DatabaseNode extends Node {

    private ScheduledExecutorService heartbeatTimer;

    private final Map<String, String> pendingRequests = new ConcurrentHashMap<>();

    private final PaxosEngine paxosEngine;
    private final InMemoryDatabase database;

    public DatabaseNode(
            String nodeId,
            List<MessageReceiver> receivers,
            NetworkRouter router,
            int quorumSize
    ) {
        super(nodeId, receivers, router);

        this.database = new InMemoryDatabase();

        DatabaseStateMachine stateMachine = new DatabaseStateMachine(database, (response, protocol) -> {
            // this lambda function is passed down to the statemachine, so it can callback when the operation is applied
            if (pendingRequests.remove(response.messageId()) != null) {
                router.send(response, protocol);
            }
        });

        this.paxosEngine =
                new PaxosEngine(
                        nodeId,
                        quorumSize,
                        stateMachine,
                        router
                );

        for (MessageReceiver receiver : this.receivers) {
            receiver.setMessageHandler(this::processMessage);
        }
    }

    private Message processMessage(Message message, Protocol protocol) {

        switch (message) {

            case ApplicationCommand command -> handleApplicationCommand(command, protocol);

            case PaxosCommand paxosCommand -> paxosEngine.handle(paxosCommand, protocol);

            case Heartbeat heartbeat -> { return null; } // ignores incoming heartbeats

            default ->
                    System.out.println(
                            "[DB] Unsupported message: "
                                    + message.getClass()
                                    .getSimpleName()
                    );
        }

        return null;
    }

    private void handleApplicationCommand(ApplicationCommand command, Protocol protocol) {
        
        if ("GET".equals(command.transaction().operation())) {

            String key = command.transaction().parameters().get("key");

            ApplicationResponse getResponse = new ApplicationResponse(
                    command.messageId(),
                    this.nodeId,
                    command.senderId(),
                    command.originId(),
                    true, // success = true
                    "Node [" + this.nodeId + "] retrieved saved value: " + database.get(key)
            );
            
            router.send(getResponse, protocol);
            return;
        }

        pendingRequests.put(command.messageId(), command.senderId());

        // injecting routing metadata inside transaction for responses
        Map<String, String> enrichedParams = new HashMap<>(command.transaction().parameters());
        enrichedParams.put("_messageId", command.messageId());
        enrichedParams.put("_originId", command.originId());
        enrichedParams.put("_replyTo", command.senderId());
        enrichedParams.put("_nodeId", this.nodeId);

        Transaction enrichedTransaction = new Transaction(command.transaction().operation(), enrichedParams);
        
        try {
            paxosEngine.proposeValue(enrichedTransaction, protocol);
        
        } catch (IllegalStateException e) {

            // paxos rejected the request for some reason
            pendingRequests.remove(command.messageId());

            ApplicationResponse failResponse = new ApplicationResponse(
                    command.messageId(),
                    this.nodeId,
                    command.senderId(),
                    command.originId(),
                    false, // success = false
                    e.getMessage() // message generated by the paxos engine
            );
            
            router.send(failResponse, protocol);
        }
    }

    @Override
    public void start() { 
        for (MessageReceiver receiver : receivers) {
            receiver.start();
        }
        System.out.println("[" + nodeId + "] Database Node started.");

        startHeartbeat();
     }

    @Override
    public void stop() { 
        for (MessageReceiver receiver : receivers) {
            receiver.stop();
        }
        if (heartbeatTimer != null) {
            heartbeatTimer.shutdownNow();
        }
        System.out.println("[" + nodeId + "] Database Node stopped.");
    }

    private void startHeartbeat() {
        this.heartbeatTimer = Executors.newSingleThreadScheduledExecutor();
        heartbeatTimer.scheduleAtFixedRate(() -> {
            Heartbeat hb = new Heartbeat(
                    java.util.UUID.randomUUID().toString(),
                    this.nodeId,
                    "*", // target is always the gateway
                    this.nodeId
            );
        
            // always sends heartbeat via udp
            this.router.send(hb, Protocol.UDP); 
            
        }, 0, 3, TimeUnit.SECONDS); // beats every 3 seonds
    }

    public InMemoryDatabase getDatabase() {
        return database;
    }
}